version: "3"
services:
  frontend:
    container_name: frontend
    tty: true
    restart: always
    build: 
      context: ./client
      dockerfile: ./Dockerfile.dev  
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - ./client/node_modules:/app/node_modules